---
version: "0.2"
language: en_US
caseSensitive: false
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - go
  - python
  - bash
words:
  - addler
  - admissionregistration
  - apeiros
  - apiextensions
  - apiserver
  - apiservers
  - apiservice
  - apko
  - approle
  - archs
  - Automerge
  - awsuswest
  - bargauge
  - behaviour
  - beholdenkey
  - Beyla
  - cadvisor
  - certmanager
  - certmanagerconfig
  - certwatcher
  - cloudnative
  - clustername
  - clusterrole
  - clusterrolebinding
  - clusterrolebindings
  - clusterroles
  - compositeresourcedefinition
  - compositeresourcedefinitions
  - Containeer
  - CONTROLPLANE
  - controlplanes
  - Coredns
  - cpus
  - CPUS
  - crds
  - creds
  - crossplane
  - customresource
  - customresourcedefinitions
  - datasource
  - datawave
  - delelete
  - deleleted
  - distroless
  - dotenv
  - envcfg
  - environmentconfig
  - environmentconfigs
  - finalizers
  - Fluentbit
  - fluxcd
  - forgelabs
  - FOWNER
  - gitops
  - gnet
  - GOMAXPROCS
  - GOMEMLIMIT
  - goroutines
  - groupname
  - htttps
  - hyperscaler
  - Hyperscaler
  - imagesafe
  - incluster
  - ingresscert
  - inotify
  - Invocatios
  - ipairs
  - jsonnet
  - kpfnk
  - Kubebuilder
  - kubeconfig
  - Kubelet
  - Kyverno
  - lameduck
  - loadbalance
  - managedresource
  - markdownlint
  - markus
  - mayastor
  - memstats
  - metricsserver
  - mjmc
  - moa
  - moaas
  - mrvsn
  - Multus
  - mutatingwebhookconfigurations
  - nfscsi
  - nfscsiconfig
  - nfsvers
  - nonroot
  - nzhjh
  - opencontainers
  - openebs
  - openebses
  - osss
  - podinfo
  - providerrevisions
  - Pulumi
  - Pyroscope
  - Quentile
  - readyz
  - resolv
  - rgba
  - rolebindings
  - Rollouts
  - schweig
  - seccomp
  - serviceaccounts
  - servicelb
  - SETGID
  - siderolabs
  - smartquotes
  - Solidtime
  - Spegel
  - submatches
  - talosconfig
  - talosctl
  - taskfile
  - Taskfile
  - taskfiles
  - tfstate
  - timepicker
  - Tradecraft
  - traefik
  - trufflehog
  - trufflesecurity
  - upbound
  - upjet
  - uptest
  - UPTEST
  - validatingwebhookconfigurations
  - vcluster
  - Virt
  - Volsync
  - wolfi
  - workqueue
  - wsize
  - xargocd
  - xcertmanager
  - xcertmanagerconfig
  - xcilium
  - xcoredns
  - xdns
  - xflux
  - xharbor
  - xmetrics
  - xmetricsserver
  - xnfscsi
  - xnfscsiconfig
  - xopenebs
  - xosss
  - xpkg
  - xpodinfo
  - xrds
  - xxcoredns
  - yamlfmt
  - Zitadel
