---
name: "Research & Development Request"
description: "Request research and development on potential features and practices."
title: "R&D Request: [Enter a descriptive title]"
labels: ["research", "R&D"]
body:
  - type: markdown
    attributes:
      value: |
        ## Research & Development Request Guidelines

        Please provide detailed information about the feature or practice you want to research and develop:

        - **Define** the current and target conditions.
        - **Describe** the potential business value and expected benefits.
        - **Consider** the security, compliance, and scalability implications.
        - **Plan** the research approach and outline the development plan if applicable.

  - type: input
    id: feature_name
    attributes:
      label: "Feature Name"
      description: Provide a short, descriptive name for the feature."
      placeholder: "e.g., New Authentication Method"
    validations:
      required: true

  - type: textarea
    id: current_condition
    attributes:
      label: "Current Condition"
      description: Describe the current problem or limitation that this research aims to address."
      placeholder: "What is the current problem or state?"
    validations:
      required: true

  - type: textarea
    id: target_condition
    attributes:
      label: "Target Condition"
      description: Describe the desired outcome or goal of the research."
      placeholder: "What should the outcome look like?"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: Provide a detailed description of the feature, including context and the problem it aims to solve."
      placeholder: "A clear and concise description of the feature..."
    validations:
      required: true

  - type: textarea
    id: business_value
    attributes:
      label: "Business Value"
      description: Explain the business value or expected benefits of this feature."
      placeholder: "Describe the business impact and alignment with strategic goals."
    validations:
      required: true

  - type: dropdown
    id: research_priority
    attributes:
      label: "Research Priority"
      description: Indicate the priority level for this research request."
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: checkboxes
    id: research_aspects
    attributes:
      label: "Research Aspects"
      description: Select the aspects to be covered during the research phase."
      options:
        - label: Market Analysis
        - label: Technical Feasibility
        - label: Cost Analysis
        - label: Risk Assessment
        - label: Security Assessment
        - label: Compliance Review
        - label: Scalability Evaluation

  - type: textarea
    id: research_plan
    attributes:
      label: "Research Plan"
      description: Outline the plan for conducting the research, including steps and methodologies."
      placeholder: "Describe the research approach and steps in detail."
    validations:
      required: true

  - type: textarea
    id: platform_impact
    attributes:
      label: "Platform Impact"
      description: Specify the components or services that might be affected by this feature."
      placeholder: "Which platform components are impacted (e.g., API Gateway, CI/CD Pipeline)?"
    validations:
      required: false

  - type: textarea
    id: security_implications
    attributes:
      label: "Security Implications"
      description: Identify any potential security concerns related to this feature."
      placeholder: "Describe any security implications."
    validations:
      required: false

  - type: textarea
    id: compliance_consideration
    attributes:
      label: "Compliance Consideration"
      description: Indicate any regulatory or compliance-related impacts."
      placeholder: "Describe any compliance considerations."
    validations:
      required: false

  - type: textarea
    id: scalability_consideration
    attributes:
      label: "Scalability Consideration"
      description: Describe any scalability or performance impacts identified during the research."
      placeholder: "How will this feature impact scalability?"
    validations:
      required: false

  - type: textarea
    id: development_plan
    attributes:
      label: "Development Plan"
      description: Provide a preliminary plan for the development phase, if applicable."
      placeholder: "Outline the development steps and initial implementation plan."
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: List any dependencies or related projects that may impact this request."
      placeholder: "Mention any dependencies on other features, teams, or external systems."
    validations:
      required: false

  - type: input
    id: estimated_effort
    attributes:
      label: "Estimated Effort"
      description: Provide an estimate of the effort required for research and development."
      placeholder: "e.g., 5 hours, 3 days, 2 weeks"
    validations:
      required: true

  - type: input
    id: target_date
    attributes:
      label: "Target Date"
      description: Specify the target date for completing the research and development activities."
      placeholder: "e.g., MM/DD/YYYY"
    validations:
      required: true

  - type: textarea
    id: next_step
    attributes:
      label: "Next Step"
      description: Suggest a next step or action for moving forward with the research."
      placeholder: "Suggested next step or experiment."
    validations:
      required: false

  - type: textarea
    id: risks_and_assumptions
    attributes:
      label: "Risks and Assumptions"
      description: Identify any risks or assumptions associated with this research request."
      placeholder: "Describe potential risks or underlying assumptions."
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: "Additional Information"
      description: Provide any additional context or supporting information for this request."
      placeholder: "Include any extra details, screenshots, or attachments."
    validations:
      required: false
